### ISSUE TITLE
[i18n] Crowdin languages

### ISSUE THREAD

**Issue by ovari** [PhoenicisOrg/phoenicis#1749] opened 2019-01-09 12:48 UTC
Please add all possible translations for PlayOnLinux to Crowdin. This can help more people localize your program. For example, Mail Redirect has all languages listed (even if they are 0% translated):
https://crowdin.com/project/mail-redirect
POL should do the same at:
https://crowdin.com/project/phoenicis
https://crowdin.com/project/phoenicis-scripts

What do you think?

Thank you

**Comment by plata** [comment] 2019-01-09 17:22
I don't think it makes sense to add all languages. It will only create bloat. If a new language is requested (either on GitHub or Crowdin), we add it very rapidly.

**Comment by qparis** [comment] 2019-01-09 21:49
Not sure, because if you don't add them, people are not aware that they could potentially exist

**Comment by Kreyren** [comment] 2019-01-10 07:32
I'm for adding them in crowdin too afaik it self-regulates to final version and more people would contribute to it.

**Comment by Kreyren** [comment] 2019-01-10 07:33
Also recommends adding tlhlngan-Hol localization

![image](https://user-images.githubusercontent.com/11302521/50952997-f7be8e80-14a9-11e9-94bd-4e67d76cb91a.png)

**Comment by madoar** [comment] 2019-01-10 09:40
I'm fine either way.

The issue with adding to many languages in my opinion is, that it can scare potential helpers away.
For example would you think a project is actively maintained if Crowdin tells you that 80% - 90% of the shown translation languages contain no actual translations? The same is true with the Crowdin badge we show on our `README`. If we add more untranslated languages the number decreases, which may have a bad influence on possible translators/helpers.

**Comment by ovari** [comment] 2019-01-10 09:48
Your project is not found if the language is not available to be translated:
https://crowdin.com/projects#advanced-search

### Afrikaans
![Afrikaans](https://user-images.githubusercontent.com/17465872/50960116-b74a2980-1518-11e9-9408-e16a77c3f058.png)

### Hungarian
![Hungarian](https://user-images.githubusercontent.com/17465872/50960163-d2b53480-1518-11e9-9ac7-f9de97da8d6e.png)

**Comment by ovari** [comment] 2019-01-10 09:50
@plata, you seem to only merge the translations from Crowdin once a locale is ~100%, so there should not be bloat in the released project.

**Comment by Kreyren** [comment] 2019-01-10 09:52
I would be even for bloated, based on my experience community for projects alike is very active.

**Comment by ovari** [comment] 2019-01-10 09:52
@madoar, you could remove the translation badge as there is a link stating the Crowdin.
https://github.com/PhoenicisOrg/phoenicis/#translate

**Comment by madoar** [comment] 2019-01-10 09:57
@ovari we have no rule when to merge the translations. The issue is just that currently with my refactoring we have quite a few commits from @PhoenicisBot because of changes to the translation context. In addition we often forget about merging the translations, because we're working on either the main application (Phoenicis) or its scripts.

If you require the translations merged simply tell us and we I think we can do it faster.

**Comment by madoar** [comment] 2019-01-10 09:58
I know we could remove the translation badge, but doesn't everyone like to see progress statistics? I like numbers larger 80%, and even more larger 90% :P

**Comment by ovari** [comment] 2019-01-10 10:02
This was about helping translators find your project. The search feature in Crowdin won't find your project. The search feature also has open-source project selector to make it easier to find your project. However, you need to list the language the translator is looking to translate into for Crowdin search to list your project.

Yes, statistics are nice when they are closer to 100%. However, since POL5 has been years in the making since POL4, wouldn't it be great to get better marker exposure?

Our 2 cents.

**Comment by Kreyren** [comment] 2019-01-10 11:35
@madoar Give me tlhlngan-Hol so that i can move close to 90% again and finish it based on user experience :D

**Comment by plata** [comment] 2019-01-10 16:39
@Kreyren that language doesn't exist in Crowdin.

**Comment by plata** [comment] 2019-01-10 16:41
@ovari I wasn't aware that we are not shown if the language does not exist.

**Comment by plata** [comment] 2019-01-10 16:42
I have now added the "top 30" languages. Should be enough. If any other language is required, it should be requested. I don't want to have 100 languages nobody is every using.

**Closed by plata** 2019-01-10 16:42 UTC
Labels: Localization

**Comment by ImperatorS79** [comment] 2019-01-10 17:07
@plata maybe @Kreyren is asking about the klingon language, which exists ^^.

**Comment by plata** [comment] 2019-01-10 17:11
Yeah, know it was about klingon but checked only tlhlngan-Hol ;P

**Comment by Kreyren** [comment] 2019-01-10 18:14
@plata Add Tlhlngan-Hol (klingon) too :3
