### ISSUE TITLE
Installation fails with failed test for maven-surefire-plugin 3.0

### ISSUE THREAD

**Issue by choallin** [PhoenicisOrg/phoenicis#2113] opened 2019-10-25 13:05 UTC
### Expected behavior
`mvn install` should install phoenicis 5

### Actual behavior
Installation fails with following error message:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project phoenicis-javafx: There are test failures.

### Steps to reproduce
Either run `mvn install` or `mvm clean package`

### System information
* software version (git revision) of phoenicis and scripts repositories
I am running on HEAD right now (00dad34402c462d898094da4d6523ba220fe5823)
* used operating system
Ubuntu 19.04
* used Java version
openjdk 13 2019-09-17

---
At first I tried to install the deb file but this didn't work either because of a missing class

**Comment by plata** [comment] 2019-10-27 10:26
That's strange. Apparently, it works in travis. If you're only interested in building, you can use `mvn -DskipTests install`.

**Comment by zwastik** [comment] 2019-11-20 21:59
os: archlinux
installed packages:
java: jdk-openjdk 13.0.1.u9-1
openfx: java-openjfx 13.u14-1
maven: maven 3.6.2-1



```
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.phoenicis.javafx.AppConfigurationInitialisationTest
java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at org.testfx.util.WaitForAsyncUtils$ASyncFXCallable.get(WaitForAsyncUtils.java:715)
        at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:298)
        at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:245)
        at org.testfx.api.FxToolkit.setupFixture(FxToolkit.java:202)
        at org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation(AppConfigurationInitialisationTest.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 30.787 s <<< FAILURE! - in org.phoenicis.javafx.AppConfigurationInitialisationTest
[ERROR] testAppConfigurationInitialisation(org.phoenicis.javafx.AppConfigurationInitialisationTest)  Time elapsed: 30.494 s  <<< FAILURE!
java.lang.AssertionError
        at org.phoenicis.javafx.AppConfigurationInitialisationTest.testAppConfigurationInitialisation(AppConfigurationInitialisationTest.java:52)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   AppConfigurationInitialisationTest.testAppConfigurationInitialisation:52
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for phoenicis 5.0-SNAPSHOT:
[INFO]
[INFO] phoenicis .......................................... SUCCESS [  2.514 s]
[INFO] phoenicis-configuration ............................ SUCCESS [ 12.942 s]
[INFO] phoenicis-entities ................................. SUCCESS [  2.003 s]
[INFO] phoenicis-multithreading ........................... SUCCESS [  2.316 s]
[INFO] phoenicis-win32 .................................... SUCCESS [  1.659 s]
[INFO] phoenicis-tools .................................... SUCCESS [ 11.505 s]
[INFO] phoenicis-repository ............................... SUCCESS [  3.744 s]
[INFO] phoenicis-scripts .................................. SUCCESS [  0.392 s]
[INFO] phoenicis-library .................................. SUCCESS [  0.259 s]
[INFO] phoenicis-engines .................................. SUCCESS [  0.284 s]
[INFO] phoenicis-settings ................................. SUCCESS [  0.145 s]
[INFO] phoenicis-containers ............................... SUCCESS [  0.253 s]
[INFO] phoenicis-javafx ................................... FAILURE [ 35.008 s]
[INFO] phoenicis-cli ...................................... SKIPPED
[INFO] phoenicis-dist ..................................... SKIPPED
[INFO] phoenicis-tests .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2019-11-20T17:06:39-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project phoenicis-javafx: There are test failures.
[ERROR]
[ERROR] Please refer to /home/oiu7/.cache/pikaur/build/playonlinux5-git/src/playonlinux5/phoenicis-javafx/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :phoenicis-javafx
==> ERROR: A failure occurred in build().
    Aborting...

Command 'makepkg --force' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
[e] edit PKGBUILD
------------------------
[s] skip building this package
[a] abort building all the packages
>

```

**Comment by madoar** [comment] 2019-11-25 21:03
@zwastik this is an error message which we strangely get every now and then. It just tells you that for some reason a test didn't terminate in a certain time interval. You can either retry or execute `mvn clean package -DskipTests`

**Comment by plata** [comment] 2019-12-28 12:54
Closing as duplicate of #2142.

**Closed by plata** 2019-12-28 12:54 UTC
