### ISSUE TITLE
Graphical Glitches

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1713] opened 2019-01-03 19:28 UTC
https://youtu.be/lO0jxuNnj1M?t=136

afaik this is very common problem in java i've never saw an app that woudn't have this issue.
reference: https://youtu.be/5dWgQe-pg6Q?t=8
reference(?): https://stackoverflow.com/questions/22737535/swing-rendering-appears-broken-in-jdk-1-8-correct-in-jdk-1-7
reference(?): https://stackoverflow.com/questions/16545982/java-swing-not-rendering-correctly
reference(?): https://stackoverflow.com/questions/17517468/how-can-i-diagnose-strange-opengl-glitches

### Expected behavior
To render GUI correctly if out of focus or when obstructed by other windows it called (steam in this example)

### Actual behavior
GUI glitches

### Steps to reproduce
git phoenicis-master -> compile it and install it -> try to install steam once steam window appears drag it across phoenicis window.

### System information
https://paste.pound-python.org/show/EwIUygXmA5cab2jEOMJl/
GPU : AMD Pitcairn XT [Radeon HD 7870 GHz Edition], DRM 3.26.0, LLVM 7.0.1
Driver : AMDGPU (open-source)
Mesa : 18.3.1
DRM : 3.26.0
LLVM : 7.0.1
OpenGL ES :  3.2
*adding info on demand*

EDIT: i tried to provide references to the best of my ability they may be outdated/obsolete

**Comment by qparis** [comment] 2019-01-03 19:40
Thank you for your report. The references are not valid since they are not using the same rendering library than we are (Swing vs. JavaFX) and the problems are not the same.

Concerning your problem, this definitely looks like hardware rendering issue, since the interface of the app is GPU accelerated. Can you provide more information about your hardware and drivers?

Many thanks

**Comment by Kreyren** [comment] 2019-01-03 23:41
@qparis Updated init, sufficient?

**Comment by Kreyren** [comment] 2019-01-04 09:55
kreyren@dreamon ~ $ wgetpaste -c "glxinfo | grep 'OpenGL'"
https://paste.pound-python.org/show/9ki46TNY3AV5W52EG7up/

**Comment by qparis** [comment] 2019-01-05 16:33
@madoar @plata Can you reproduce this bug?

**Comment by madoar** [comment] 2019-01-05 17:03
I can't reproduce this.

**Comment by plata** [comment] 2019-01-05 18:44
No.

**Comment by plata** [comment] 2019-01-30 15:59
Closing because it doesn't seem to be a Phoenicis issue.

**Closed by plata** 2019-01-30 15:59 UTC
Labels: bug

**Comment by Kreyren** [comment] 2019-01-31 09:06
Building new OS atm. will verify again after.

Please share your system configuration that is relevant to this issue i try to reproduce it.
