### ISSUE TITLE
Add ability to install Verbs in existing container

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1440] opened 2018-10-27 12:18 UTC
Hello, I would like to be able to install additional components into container like fonts, dotnet, DirectX.

I know that I can install it during app installation, but for example that app updates and I will require another packages / components, then I want to be able to install additional components into existing container like in POL 4.

**Comment by plata** [comment] 2018-10-27 16:01
This can be implement similarly to engine tools.

**Comment by t0msk** [comment] 2018-10-27 16:16
What do you mean? I imagine that you open containers tab, then click on container and there would be new panel called for example "Components" and there you could install / uninstall components and you could see list of installed components.

**Comment by ImperatorS79** [comment] 2018-10-27 16:28
Linked to [https://github.com/PhoenicisOrg/scripts/issues/534](https://github.com/PhoenicisOrg/scripts/issues/534)

**Comment by plata** [comment] 2018-10-27 18:01
Didn't have that in mind. I will close this issue.

**Closed** 2018-10-27 18:01 UTC
Labels: feature-request

**Comment by t0msk** [comment] 2018-10-28 11:39
That's sad, because that is the most important feature for me.

**Comment by t0msk** [comment] 2018-10-28 19:11
@plata If you don't want to implement this very important feature, then please you could implement Winetricks at least into Wine tools panel. with Winetricks it is possible to install components.

**Comment by qparis** [comment] 2018-10-28 19:37
@t0msk This issue has been closed because it is duplicate of  PhoenicisOrg/scripts#534

**Comment by plata** [comment] 2018-10-29 16:42
Exactly. Only to avoid duplicates. Doesn't mean that it will not be implemented.
