### ISSUE TITLE
openjdk/openjfx on fedora

### ISSUE THREAD

**Issue by Tutul-** [PhoenicisOrg/phoenicis#1157] opened 2018-02-13 17:15 UTC
I saw that one coming from a while but : it seem that openjdk/openjfx on fedora have some difficulty to run phoenicis. As far as I know, it's probably linked with the "No proprietary code" mojo of Fedora.
I'm missing webkit javafx library `libjfxwebkit.so` and get error symbol with native library. It's strange because I get one error about a native library symbol but the lib is installed
```
/usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_iio.so: undefined symbol: jpeg_resync_to_restart
```
I suppose libjfxwebkit.so use not full open source code :/
Can someone confirm ?

**Comment by Tutul-** [comment] 2018-02-13 17:23
Ok find something, webkit depend on media, and media depend on ffmpeg. And ffmpeg isn't trully open source so it isn't on the main repo. :/
I guess, one day, that many problem will make me change to some other distribution >>

**Comment by plata** [comment] 2018-02-13 17:43
Do you see any solution for this on our side? I wouldn't like to tell Fedora users that they just can't use Phoenicis.

**Comment by Tutul-** [comment] 2018-02-13 17:51
I try but for now rpmfusion (a repo with non-free and free-with-non-free-lib) is down so I can't check if openjfx is within. An other solution is to build openjfx on fedora. I use to build it when v5 started because openjfx wasn't enougth free

**Comment by plata** [comment] 2018-02-14 09:35
Have you tried: https://github.com/gferon/openjfx-fedora?

If you got it working, let me know how so that we can add an installation description for Fedora in the wiki.

**Comment by Tutul-** [comment] 2018-02-14 10:21
webkit compile but without media. I suppose it can work as long as we don't need it.
btw, I'll move to manjaro in the week, too many restriction with fedora for some software.

**Comment by plata** [comment] 2018-02-14 10:23
So you got it running without the media stuff?

**Comment by ekultails** [comment] 2018-06-13 03:02
Tutul, you're absolutely right. Fedora strives to be a fully open-source operating system for the community and that means not providing proprietary software in the default repositories. [1] Red Hat understands the usefulness of having additional repositories so in Fedora 28 users can opt-in to enable a few verified third-party repositories. [2]

The only reliable way to get Phoenicis working on Fedora is to use Oracle Java instead of OpenJDK. This includes the full JavaFX library. The official Fedora wiki page on how to install Oracle Java should be linked where ever the build documentation for Phoenicis is. [3]  I have tested this out and installed a few Windows applications with Phoenicis and it works great.

1. https://fedoraproject.org/wiki/Forbidden_items?rd=ForbiddenItems
2. https://fedoraproject.org/wiki/Workstation/Third_Party_Software_Repositories
3. https://fedoraproject.org/wiki/JDK_on_Fedora#Installing_Oracle_JDK_on_Fedora

**Comment by plata** [comment] 2018-06-13 15:06
@ekultails would you mind providing a pull request which describes this in the documentation?

**Comment by Tutul-** [comment] 2018-06-13 19:34
Oracle will drop javafx support, and that will become a third party library.
I'm not sure it's the best move. Maybe we can find a full openjfx package that can run on Fedora.
I plan to install a VM with Fedora for testing purpose (since I move to Manjaro).

**Comment by ekultails** [comment] 2018-06-14 01:05
Thanks for that feedback, that's good to know about Oracle dropping support for JavaFX. It sounds like this is where we're at right now:

* Short-term solution: Suggest end-users use Oracle Java for testing out the upcoming alpha release of Phoenicis. @plata I'll work on a documentation update for that.
* Long-term solution: Find and build a reliable OpenJFX package that can be part of an RPM repository alongside Phoenicis packages (or find a third-party repository that provides it).

The more eyes and testing we can get on this, the better. Thanks for your assistance @Tutul- !

**Comment by plata** [comment] 2018-06-14 15:49
There's one more thing we should do: check if we really require the parts of JavaFX which are not available in the Fedora packet. Maybe we can live without it.

**Comment by qparis** [comment] 2018-06-14 16:36
I don’t fully understand the errors, but if the problem is about libjfxwebkit, then I suspect that the WebView is the problem. What do you think ?

**Comment by plata** [comment] 2018-06-14 18:21
I assume the same but I cannot test it because I don't have that problem on Ubuntu.

**Comment by Tutul-** [comment] 2018-06-15 10:36
If I remember, that was WebView

**Comment by plata** [comment] 2018-06-15 15:54
I think we only use the WebView for the presentation in the install wizard and the app description. We could maybe replace that with a [HTMLEditor](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/web/HTMLEditor.html). Do you know if that would be available on Fedora?

**Comment by plata** [comment] 2018-06-15 16:51
For reference, here's the bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1547378.

@qparis from the bug report, I cannot see that this is a problem of something not being completely free or open. It rather seems that simply nobody is willing to build the library properly. In this case, we really should not care.

**Comment by ekultails** [comment] 2018-06-15 17:31
Excellent find @plata ! I am inquiring in that external bug report on what is required to get this properly setup in Fedora "the right way." Perhaps if we get enough Linux gamers to show their support for Phoenicis I can use that to help put some pressure internally here at Red Hat to get this implemented. ;-)

**Comment by Tutul-** [comment] 2018-06-15 17:55
When I try it, was using a custom build only system

**Comment by madoar** [comment] 2018-06-16 08:36
@plata is it really required to have the text formatted?
I must confess, that I believe the html in the translations to be annoying.

**Comment by plata** [comment] 2018-06-16 09:06
Maybe not. Can you do comparison screenshots with/without formatting?

**Comment by plata** [comment] 2018-10-18 17:33
@Tutul- is this still happening with OpenJFX11?

**Comment by Tutul-** [comment] 2018-10-21 13:15
I can't build for now. An error with the javafx test. About a bad class version.

**Comment by Tutul-** [comment] 2018-10-21 13:18
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project phoenicis-javafx: Compilation failure
[ERROR] /home/tutul/Documents/phoenicis/phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/common/ColumnConstraintsWithPercentage.java:[21,27] cannot access javafx.scene.layout.ColumnConstraints
[ERROR]   bad class file: /home/tutul/.m2/repository/org/openjfx/javafx-graphics/11/javafx-graphics-11-linux.jar(javafx/scene/layout/ColumnConstraints.class)
[ERROR]     class file has wrong version 54.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by plata** [comment] 2018-10-21 13:30
No idea. Never saw that before.

**Comment by Tutul-** [comment] 2018-10-21 13:30
Look like one class in the javafx repo is compiled for 1.8
I'll try again with a fully clean repo

**Comment by plata** [comment] 2018-11-25 11:51
@Tutul- is this still valid with Java 10/11 and OpenJFX? Is there anything we could/should do about this issue or can it be closed?

**Comment by ImperatorS79** [comment] 2018-12-07 09:05
Compilation and execution works for me on fedora 29 (used `java-11-openjdk-dev` and `export JAVA_HOME="/usr/lib/jvm/java-11-openjdk"`). You have to use the X.org session.

**Comment by Tutul-** [comment] 2018-12-07 12:43
Seem good as @ImperatorS79 write. But I needed to use `sudo update-alternatives --config java` to use java 11 (JAVA_HOME wasn't enough but that's normal if you have more than one jvm installed).

So we cannot run on Wayland (for now ?).

**Comment by ImperatorS79** [comment] 2018-12-07 13:35
javafx does not support wayland, and only works under xwayland with `-Djdk.gtk.version=2` [https://github.com/javafxports/openjdk-jfx/issues/175](https://github.com/javafxports/openjdk-jfx/issues/175).

This is not really a problem since wine itself cannot work under wayland at the moment.

**Comment by plata** [comment] 2018-12-07 21:54
Is there anything you want to add to the documentation so that we can close this issue?

**Comment by Tutul-** [comment] 2018-12-08 00:19
nothing more for me

**Closed** 2018-12-08 17:06 UTC
