### ISSUE TITLE
Local install not working

### ISSUE THREAD

**Issue by dstar** [PhoenicisOrg/phoenicis#2307] opened 2021-01-01 04:51 UTC
### Expected behavior
After installing something using 'Local Installer' (in this case, Might and Magic 9 from GOG), it is available to run
### Actual behavior
After selecting the installler, it runs successfully, but when it exits, the local installer goes back to the 'Please select the executable' pane, and I can't continue. I'm not sure if I'm doing something wrong, or what....
### System information
* I installed the flatpack from the link
* Linux Mint 20
* OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by plata** [comment] 2021-01-01 11:09
This is intended behavior. The problem is: Phoenicis cannot know, which executable it should use to run Might and Magic 9. So you must tell it. To be clear: "Please select the executable" is about the game executable (e.g. `MightAndMagic9.exe`) and not about the installer.

In general: I would always advice to write a script for any app you want to use once you know what's required to run it. It's quite simple: https://github.com/PhoenicisOrg/scripts/blob/master/Applications/Games/XIII/GOG/script.js

**Comment by dstar** [comment] 2021-01-03 03:19
Ah! That makes a lot of sense. I'd suggest changing the wording of the dialogs, but to be honest, over the last two days the only thing I've been able to come up with is to explicitly reference 'installer' in the first dialog, and... _maybe_ something like 'executable to run' on the second, which frankly doesn't help much at all. What do you expect, though, I'm a programmer, and I end up with interfaces designed by a programmer, you know, designed to tear your eyes out.

Maybe someone else can come up with something better?

**Comment by plata** [comment] 2021-01-04 15:18
As the original issue is clarified, I will close this. Feel free to open a new issue to improve the wording if you have any idea.

**Closed by plata** 2021-01-04 15:18 UTC
