### ISSUE TITLE
Phonics-javafx

### ISSUE THREAD

**Issue by AireagoirSteam** [PhoenicisOrg/phoenicis#2078] opened 2019-09-01 15:22 UTC
### Expected behavior
Build completion
### Actual behavior
Build failure
### Steps to reproduce
mvn clean package
### System information
* software version (git revision) of phoenicis and scripts repositories
* used operating system
Ubuntu 18.04.3
* used Java version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

Output from terminal
[log.txt](https://github.com/PhoenicisOrg/phoenicis/files/3563637/log.txt)

Currently unable to build phoenicis on a fresh ubuntu vm with java

**Comment by madoar** [comment] 2019-09-01 19:05
Don't worry about the error you are getting. It is because of a timing issue which sometimes occurs inside a test. It doesn't affect Phoenicis.

If you try build Phoenicis again it should work. If it does not you can simply skip the tests by running:

```
mvn clean package -DskipTests
```

Feel free to tell us if you face any other issues.

**Comment by AireagoirSteam** [comment] 2019-09-01 22:36
Thank you skipping the tests works and I get a successful build.

I am wondering though since gitpod is available could vagrant be a possable consideration in the future for building perhaps?

**Comment by plata** [comment] 2019-09-02 17:21
Which advantages would it offer to us?

**Comment by AireagoirSteam** [comment] 2019-09-04 13:20
@plata it would allow for (in my opinion at least) easier building locally and also isolation dependency wise since it is easier to use than say docker. 

Additionally no matter the machine phoenicis could be built locally which would make things easier for packagers.

**Comment by plata** [comment] 2019-09-04 16:11
I've never used vagrant myself so far so I would have to dig into it. However, if someone would go ahead and provide Vagrant support in a pull request, I don't see a reason not to use it ;).

**Comment by plata** [comment] 2019-12-28 12:55
Closing as duplicate of #2142.

**Closed by plata** 2019-12-28 12:55 UTC
